
== Acta Reunió

[options="header"]

[cols="20%, 80%"]
|===
h| *Data, Hora*   | 20/10/2020
h| *Lloc*         | INS Nicolau Copernic 
h| *Assistents*   a|*Presents* 

* Marc
* Oriol
* Diego
* Pablo 

*No Presents*

* Oscar

h| Versió del document| Ver2.0  pendent d'aprovació
h|Ordre del dia a|

. Requisits
. Cens d'actors
. Casos d'us 
. Glosari de conceptes
2.1+h|Detalls 
2.1+h|Punt 1
h|1.1  | Requisits fincionals
h|1.2  | Requisits no funcionals

2.1+h|Punt 2
h|2.1  |Alumne
h|2.2  |Profesor
h|2.3  |Administrador


2.1+h|Punt 3
h|3.1|Iniciar sessió
h|3.2|Baixa i alta usuari
h|3.3|Modificar dades usuari
h|3.4|Crear/Esborrar activitat
h|3.5|Importar/Exportar activitat
h|3.6|Gestionar incidencies
h|3.7|Veure estadistiques usuari/Activitat


2.1+h|Punt 4
h|4.1|Especificació del Glossari


2.1+h|Acords
h|1|Posibilitat activitats ya fetes
h|2|Idea Opcional
h|Data següent reunió|<27/10/2020>


2.1+h|Observacións
h|1|Evaluació amb rúbica o similar
h|2|Activitats gamificades
h|3|Plantilles d'activitats
h|4|Pagina reprogramable
h|5|Pagina responsive

