INSERT INTO ACTIVIDAD VALUES(null, "ACTIVIDAD 1");
INSERT INTO Grupo_Tiene_Actividad VALUES(1, 1);

INSERT INTO ACTIVIDAD VALUES(null, "ACTIVIDAD 2");
INSERT INTO Grupo_Tiene_Actividad VALUES(2, 2);


INSERT INTO Pregunta VALUES(null, 1, "Prueba Pregunta 1", null);
INSERT INTO Pregunta VALUES(null, 1, "Prueba Pregunta 1.2", null);
INSERT INTO Pregunta VALUES(null, 2, "Prueba Pregunta 2", null);

/* ID RespuestaCorta, Pregunta, Actividad, texto */
INSERT INTO RESPUESTA_CORTA VALUES(null, 1, 1, "Respuesta 1");
INSERT INTO RESPUESTA_CORTA VALUES(null, 2, 1, "Respuesta 2");
INSERT INTO RESPUESTA_CORTA VALUES(null, 3, 1, "Respuesta 3");

/*
INSERT INTO RESPUESTA_CORTA VALUES(null, 2, 1, "Respuesta 1");
INSERT INTO RESPUESTA_CORTA VALUES(null, 2, 1, "Respuesta 2");
INSERT INTO RESPUESTA_CORTA VALUES(null, 2, 1, "Respuesta 3");
*/

INSERT INTO RESPUESTA_CORTA VALUES(null, 1, 2, "Respuesta 1");
INSERT INTO RESPUESTA_CORTA VALUES(null, 2, 2, "Respuesta 2");
INSERT INTO RESPUESTA_CORTA VALUES(null, 3, 2, "Respuesta 3");


INSERT INTO ENTREGA VALUES(NULL,05/02/2021);
INSERT INTO ENTREGA VALUES(NULL,05/02/2021);
INSERT INTO ENTREGA VALUES(NULL,05/02/2021);

INSERT INTO ENTREGA VALUES(NULL,05/02/2021);


INSERT INTO ESTADISTICA_ALUMNO_ACTIVIDAD VALUES(1,1,1);
INSERT INTO ESTADISTICA_ALUMNO_ACTIVIDAD VALUES(2,2,1);
INSERT INTO ESTADISTICA_ALUMNO_ACTIVIDAD VALUES(3,3,1);



INSERT INTO PREGUNTA_ALUMNO VALUES (null,1);
INSERT INTO PREGUNTA_ALUMNO VALUES (null,2);
INSERT INTO PREGUNTA_ALUMNO VALUES (null,3);


/* ID RESPUESTA, ID PREGUNTA ALUMNO, ID ESTADISTICA, TEXTO    */
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 1, 1, "Respuesta 1 Alumno");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 2, 1, "Respuesta 2 Alumno");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 3, 1, "Respuesta 3 Alumno");

INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 1, 2, "Respuesta 1");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 2, 2, "Respuesta 2");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 3, 2, "Respuesta 3");

INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 1, 3, "Respuesta 1");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 2, 3, "Respuesta 2");
INSERT INTO RESPUESTA_CORTA_ALUMNO VALUES(null, 3, 3, "Respuesta 3");

SELECT * FROM RESPUESTA_CORTA_ALUMNO;


SELECT * FROM ENTREGA;





SELECT * FROM USUARIOS;
SELECT * FROM GRUPO_TIENE_ACTIVIDAD;
SELECT * FROM USUARIO_PERTENECE_GRUPO;
SELECT * FROM ESTADISTICA_ALUMNO_ACTIVIDAD;
INSERT INTO ESTADISTICA_ALUMNO_ACTIVIDAD VALUES(4,4,2);




SELECT * FROM ACTIVIDAD a, PREGUNTA p
WHERE a.id_actividad = p.id_actividad  ORDER BY a.id_actividad;
/* CONSULTA 1 */
SELECT * FROM ENTREGA eg , ESTADISTICA_ALUMNO_ACTIVIDAD eaa, GRUPO_TIENE_ACTIVIDAD gta, ALUMNO a
WHERE eaa.id_actividad = 2 AND gta.id_grupo = 2 AND eaa.id_entrega = eg.id_entrega AND gta.id_actividad = 2 AND a.id_usuario = eaa.id_usuario;

/* CARGA LA ACTIVIDAD Y LUEGO LA PRIMERA PREGUNTA  */




SELECT * FROM ACTIVIDAD;
SELECT * FROM PREGUNTA;
SELECT * FROM PREGUNTA_ALUMNO ORDER BY id_entrega;

/* NO SELECCIONA ACTIVIDAD  
SELECT * FROM PREGUNTA_ALUMNO pa,ESTADISTICA_ALUMNO_ACTIVIDAD eaa, PREGUNTA p WHERE pa.id_entrega = 4 AND eaa.id_actividad = 1 
AND p.id_pregunta = pa.id_pregunta_alumno 
AND eaa.id_entrega = pa.id_entrega;

*/


SELECT * FROM ESTADISTICA_ALUMNO_ACTIVIDAD eaa, PREGUNTA_ALUMNO pa WHERE eaa.id_actividad = 1
AND eaa.id_entrega = 1 AND pa.id_entrega = 1;

SELECT * FROM PREGUNTA_ALUMNO pa, ESTADISTICA_ALUMNO_ACTIVIDAD eaa WHERE pa.id_entrega = 1 AND (eaa.id_actividad = 1 AND eaa.id_entrega = 1); 

SELECT * FROM ESTADISTICA_ALUMNO_ACTIVIDAD;

SELECT * FROM PREGUNTA_ALUMNO;
INSERT INTO PREGUNTA_ALUMNO VALUES (null,4);

 /*   PREGUNTAS      */
SELECT * FROM ESTADISTICA_ALUMNO_ACTIVIDAD eaa, PREGUNTA_ALUMNO pa, PREGUNTA p 
WHERE eaa.id_entrega = 1 AND pa.id_pregunta_alumno = 4 AND  (p.id_actividad = eaa.id_actividad AND p.id_actividad = 1);

/*  ENTREGAS    */


