USE EduPrim;
SELECT * FROM ACTIVIDAD;
SELECT * FROM USUARIOS WHERE tipo = "ALU";
SELECT * FROM ENTREGA_ALUMNO_ACTIVIDAD;
SELECT * FROM PREGUNTA_ALUMNO;
SELECT * FROM PREGUNTA WHERE id_actividad = 1;
SELECT * FROM RESPUESTA_CORTA WHERE id_actividad = 1;
SELECT * FROM ACTIVIDAD;

SELECT * FROM PREGUNTA_ALUMNO;
SELECT * FROM PREGUNTA;
SELECT * FROM GRUPO_TIENE_ACTIVIDAD;

SELECT * FROM ENTREGA_ALUMNO_ACTIVIDAD,PREGUNTA_ALUMNO WHERE PREGUNTA_ALUMNO.id_entrega = 1 AND ENTREGA_ALUMNO_ACTIVIDAD.id_actividad =1
AND ENTREGA_ALUMNO_ACTIVIDAD.id_entrega = 1;




/*INSERT INTO PREGUNTA VALUES(null,1,"Hola bb",null);*/
/*INSERT INTO PREGUNTA VALUES(2,1,"Hola bb 2",null);*/
/*INSERT INTO GRUPO_TIENE_ACTIVIDAD VALUES(1,1);*/
SELECT nombre_grupo FROM GRUPO_TIENE_ACTIVIDAD gta,ACTIVIDAD act,GRUPOS gr WHERE gta.id_actividad = act.id_actividad AND gta.id_grupo = gr.id_grupo;
/*SELECT * FROM USUARIO_PERTENECE_GRUPO;
SELECT * FROM GRUPOS;
SELECT * FROM ALUMNO, USUARIO_PERTENECE_GRUPO upg WHERE ALUMNO.id_usuario = upg.id_usuario;*/
